<?php

namespace BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestWithImage($count = 10)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        return
            $qb
                ->select('a')
                ->from('BlogBundle:Article', 'a')
                ->join('a.categories', 'c')
                ->where(
                    $qb->expr()->andx(
                        $qb->expr()->isNotNull('a.image')
                    ))
                ->orderBy('a.id', 'DESC')
                ->setFirstResult(0)
                ->setMaxResults($count)
                ->getQuery()
                ->getResult()
            ;
    }

    public function getLatestTextOnly($count = 10)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        return
            $qb
                ->select('a')
                ->from('BlogBundle:Article', 'a')
                ->join('a.categories', 'c')
                ->where(
                    $qb->expr()->andx(
                        $qb->expr()->isNull('a.image')
                    ))
                ->orderBy('a.id', 'DESC')
                ->setFirstResult(0)
                ->setMaxResults($count)
                ->getQuery()
                ->getResult()
            ;
    }
    
}
