<?php

namespace BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $count
     * @param null $except
     * @return array
     */
    public function getLatestWithImage($count = 10, $except = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb
            ->select('a')
            ->from('BlogBundle:Article', 'a')
            ->join('a.categories', 'c')
            ->where($qb->expr()->isNotNull('a.image'))
        ;

        if(is_array($except) && count($except)) {
            $qb->andWhere($qb->expr()->notIn('a.id', $except));
        }

        $qb
            ->orderBy('a.id', 'DESC')
            ->setFirstResult(0)
            ->setMaxResults($count)
        ;

        return $qb->getQuery()->getResult();
    }

    /**
     * @param int $count
     * @param null $except
     * @return array
     */
    public function getLatestTextOnly($count = 10, $except = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb
            ->select('a')
            ->from('BlogBundle:Article', 'a')
            ->join('a.categories', 'c')
            ->where($qb->expr()->isNull('a.image'))
        ;

        if(is_array($except) && count($except)) {
            $qb->andWhere($qb->expr()->notIn('a.id', $except));
        }

        $qb
            ->orderBy('a.id', 'DESC')
            ->setFirstResult(0)
            ->setMaxResults($count)
        ;

        return $qb->getQuery()->getResult();
    }
    
}
