<?php

namespace BlogBundle\Repository;

use BlogBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestArticlesForMegaMenu(Category $category)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        return
            $qb
                ->select('a')
                ->from('BlogBundle:Article', 'a')
                ->join('a.categories', 'c')
                ->where(
                    $qb->expr()->andx(
                        $qb->expr()->isNotNull('a.image'),
                        $qb->expr()->eq('c.id', $category->getId())
                    ))
                ->orderBy('a.id', 'DESC')
                ->setFirstResult(0)
                ->setMaxResults(5)
                ->getQuery()
                ->getResult()
        ;
    }
}
