<?php

namespace BlogBundle\Repository;

use BlogBundle\Entity\Article;
use Doctrine\ORM\EntityRepository;

/**
 * KeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeywordRepository extends EntityRepository
{
    public function extractArticleCategories(Article $article) {

        $content = implode(' ', array($article->getTitle(), $article->getExcerpt(), strip_tags($article->getContent())));
        $content = mb_ereg_replace('[^\آ\ا\أ\إ\ب\پ\ت\ث\ج\چ\ح\خ\د\ذ\ر\ز\ژ\س\ش\ص\ض\ط\ظ\ع\غ\ف\ق\ك\ک\گ\ل\م\ن\و\ؤ\ه\ي\ی\ئ\ء]+', ' ', $content);
        $content = explode(' ', $content);

        $keywords = $this->findAll();
        foreach($keywords as $keyword){
            if(in_array($keyword->getKeyword(), $content)){
                foreach($keyword->getCategories() as $category){
                    $article->addCategory($category);
                }
            }
        }

        $categories = $article->getCategories();
        if(!count($categories)){
            $article->addCategory($this->getEntityManager()->getRepository('BlogBundle:Category')->findOneBy(['slug' => 'تکنولوژی-و-فن-آوری']));
        }

    }
}